Make Radio Show Page header text black
daleinen7/weird-radio pull request #29
Opened 2021-11-10 00:59 UTC by elliothwang

Make Radio Show Page header text black

2021-11-10 04:34 UTC, daleinen7 requested changes
Looks really good. I definitely like the clean up you did throughout the file. Only a few minor things I'd prefer to keep as they were.

2021-11-10 04:34 UTC, daleinen7 commented on src/scss/_shows-feature.scss
> -    background: transparentize($haze, 0.5);
Let's take advantage of SCSS functions and keep transparentize in case we ever need to change the $haze variable color across the project.

2021-11-10 04:34 UTC, daleinen7 commented on package-lock.json
> -      "name": "weird-radio",
Let's keep the name property. I don' think it really makes a huge difference but it might as well be there.

2021-11-10 05:21 UTC, elliothwang commented on src/scss/_shows-feature.scss
> -    background: transparentize($haze, 0.5);
Got it! I was just going according to the Figma color.

2021-11-10 05:21 UTC, elliothwang commented on package-lock.json
> -      "name": "weird-radio",
For this one, I didn't remove it. I just installed npm & didn't put a name in the packages.

2021-11-10 05:28 UTC, daleinen7 commented on package-lock.json
> -      "name": "weird-radio",
Weird. To be honest I don't even know where it becomes relevant so it probably wouldn't be a big difference one way or the other but might as well keep it.

2021-11-10 05:34 UTC, daleinen7 commented on src/scss/_shows-feature.scss
> -    background: transparentize($haze, 0.5);
Gotcha. That's not a bad all to make. Definitely go with your gut on changes like that. That's what reviews are for so we can discuss it. I went with transparentize because it's easier to make changes to, and I thought 50% looked better with the varying backgrounds (the figma only has a saturated background). We'll see what Connie wants to do when she has time to go through it and give a more thorough review.

2021-11-19 05:27 UTC, daleinen7 approved these changes
Yep, looks good! Excellent work on this PR.

2021-11-19 06:26 UTC, merged