media player & header resizing on scroll
daleinen7/weird-radio pull request #33
Opened 2021-12-04 02:22 UTC by elliothwang

media player & header resizing on scroll. Created 'scrolled' state and change inline style of player & header based on value of 'scrolled'.

2021-12-04 05:12 UTC, daleinen7 requested changes

2021-12-04 05:12 UTC, daleinen7 commented on src/components/Header.jsx
> +    window.scrollY >= 200 ? setScrolled(true) : setScrolled(false)
Looks like this is preventing the app from deploying. We can talk about it tomorrow for a solution.

2021-12-05 19:14 UTC, elliothwang commented on src/components/Header.jsx
> +    window.scrollY >= 200 ? setScrolled(true) : setScrolled(false)
Are you getting this error: Error: error:0308010C:digital envelope routines::unsupported? Apparently, this a fairly new error & I had to work around before changing the player. 

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

2021-12-07 17:00 UTC, daleinen7 commented on src/components/Header.jsx
> +    window.scrollY >= 200 ? setScrolled(true) : setScrolled(false)
No I haven't seen it. Maybe it's something specific to your branch?

2021-12-07 17:26 UTC, daleinen7 commented on src/components/Header.jsx
> +    window.scrollY >= 200 ? setScrolled(true) : setScrolled(false)
Also we never got a chance to talk over the window.scrollY. The problem is that node is reading this, and there is no `window` object in node. It seems like the consensus is if you put it inside a useEffect hook it should be fine, but I've also done something similar in my [portfolio](https://dougleinen.com). 

Here was my implmentation
```const [windowHeight, setWindowHeight] = useState()

  useEffect(() => {
    setWindowHeight(window.innerHeight)
  }, [])
```

Let me know what you find out.

2021-12-11 00:38 UTC, closed without merging